apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: container-repo-pvc
    labels:
        app: container-repo
spec:
    accessModes:
    - ReadWriteOnce
    resources:
        requests:
            storage: {{.Values.persistence.cotainer-repo.size }}
    storageClassName: {{{{.Values.persistence.cotainer-repo.storageClass }}}}