apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: devops-pod-monitor
  namespace: monitoring
  labels:
    release: devops
spec:
  namespaceSelector:
    matchNames:
      - devops
  selector:
    matchLabels: {}  # 모든 pod 감시 (필터 없음)
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 30s
