apiVersion: v1
kind: Secret
metadata:
  name: gitea-secret
type: Opaque
data:
  # 필요 시 초기 관리자 비번 등을 넣을 수 있습니다.
  GITEA_APP_INI: "{{ \"[database]\\nDB_TYPE = sqlite3\\nPATH = /data/gitea.db\" | b64enc | quote }}"