
# 1. vaultwarden , 2fa (2차 인증), 3. wg easy (접속용)


ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: password.local
      paths: /
    - host: 2fa.local
      paths: /
    - host: wireguard.local
      paths: /

      