twoFactor:
  image: 2fa:latest  # 실제 사용하시는 이미지 이름으로 변경하세요
  replicaCount: 1
  port: 8080         # 해당 앱이 사용하는 포트로 수정
  host: 2fa.local
  # 앱에 필요한 환경변수들
  encryptionKey: "super-secret-key-123"

vaultwarden:
  adminToken: "your-very-secure-password" # 관리자 페이지 접속 비번


wireguard:
  externalIp: "1.2.3.4" # 외부 접속용 IP # ddns 주소등