apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jenkins-service-monitor
  namespace: monitoring
  labels:
    release: devops
spec:
  namespaceSelector:
    matchNames:
      - devops
  selector:
    matchLabels:
      app: jenkins # Jenkins Service에 붙은 라벨과 맞춰야 함
  endpoints:
    - port: http           # Service의 port 이름과 동일해야 함
      path: /metrics    # Jenkins metrics endpoint
      interval: 30s
# app에 promethuse 플러그인은 별도로 설정해야함.