apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: rpm-repo-pvc
    labels:
        app: rpm-repo
spec:
    accessModes:
    - ReadWriteOnce
    resources:
        requests:
            storage: {{.Values.persistence.rpm-repo.size }}
    storageClassName: {{{{.Values.persistence.rpm-repo.storageClass }}}}