apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: debian-repo-pvc
    labels:
        app: debian-repo
spec:
    accessModes:
    - ReadWriteOnce
    resources:
        requests:
            storage: {{.Values.persistence.debian-repo.size }}
    storageClassName: {{{{.Values.persistence.debian-repo.storageClass }}}}