apiVersion: v1
kind: Secret
metadata:
  name: code-server-secret
  # 다른 앱과 섞이지 않도록 네임스페이스 내에서 고유한 이름을 권장합니다.
type: Opaque
data:
  # b64enc 함수가 자동으로 인코딩을 처리합니다.
  PASSWORD: {{ .Values.codeServer.password | b64enc | quote }}