apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "workspace-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }} # 기본 1개 



containers:
  - name: gitea.local
    image: gitea:latest
    ports:
      - containerPort: 3000
  - name: code-server.local
    image: lscr.io/linuxserver/code-server:latest
  - name: jenkins.local
    image: jenkins/jenkins:lts
    ports:
      - containerPort: 4080
  - name: argocd.local
    image: argoproj/argocd:v2.7.7
    ports:
      - containerPort: 6080