apiVersion: v1
kind: Service
metadata:
  name: two-factor-service
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.twoFactor.port }}
      protocol: TCP
      name: http
  selector:
    app: two-factor