apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jenkins-service-monitor
  namespace: monitoring
  labels:
    release: devops
spec:
  namespaceSelector:
    matchNames:
      - devops
  selector:
    matchLabels:
      app: jenkins-service # Jenkins Service에 붙은 라벨과 맞춰야 함
  endpoints:
    - port: http           # Service의 port 이름과 동일해야 함
      path: /prometheus    # Jenkins Prometheus 플러그인 endpoint
      interval: 30s
