apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: devops-pod-monitor
  namespace: monitoring   # PodMonitor 리소스는 monitoring 네임스페이스에 생성
  labels:
    release: devops
spec:
  namespaceSelector:
    matchNames:
      - devops           # 실제 대상 Pod가 있는 네임스페이스
  selector: {}
  podMetricsEndpoints:
    - port: http         # Pod의 containerPort 이름과 반드시 일치해야 함
      path: /metrics
      interval: 30s
