apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-duckdns
spec:
  acme:
    email: shseo2023@example.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-duckdns
    solvers:
    - dns01:
        webhook:
          groupName: acme.duckdns.org
          solverName: duckdns
          config:
            apiTokenSecretRef:
              name: duckdns-api-token-secret
              key: token
