apiVersion: v2 # Using Helm Chart API 3 ~
name: dev-ops
description: A helm chart for personal DevOps workspace
type: application
version: 0.1.0
appVersion: "0.1.0"


maintainers:
  - name: wayfarer6
    email: shseo2023@gmail.com

keywords:
  - dev

dependencies:
  - name: monitoring
    version: 0.1.0
    repository: "file://charts/monitoring"