---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dev-ops-secret
  namespace: devops
spec:
  encryptedData:
    code-server-password: AgAEQsrwqwE7GjDM4iZcRM5qYFeJTPFQJ0etdL5kWZNJTRjoKyOuw9AxOU0X/uwsbpJYh89hc1XDDSZVN1fFyqYtvctZOJ4VtyRAitPWkUivzSCkkh+8VoDhvz6cOXR+6qbdtlqE+qPiX7f2PhtJ6sKaWWWd6s3wpkOM03vRWEvovsJYkHy+9K/BSCLXKBdcm64ZIoPMEXVb39E0qwiotU36RnkPYtnD8QTfZM9+yZezQDy9uZjr/o9GHlewGztESs3UXyG33iQLk/57PenzjWD8Qp0xN2kkEn0yBWYQRf8dU0z41SMSJJhbKAqHRyHzqeQ90oJjOCSi5XQ4fTdPvaHyIzV5XpnGCGjjMERMp4YeYOVIIToPetFgTwqUbXXmP3emDFke/jI0afp8rCjEPJtg3QjAmKNXZnIxBOFWG5lQDH+7AR+RDFpmcFqjnDwXJfGrFCtyZISVzhIXv6/o/V8593K2IkFg4PMVQUvz7T1qLp/7yq7ruDv2DsVkjxHzVntYYqSoCxtMfDG4CNkP4AITVUpENALNSsYEKsU5GDfyPglxwMLOz6vfMdVEN3SLuFZAwOXvnyUmMIjrfQOtFXqzxiGnRjPMjYS21WQyf8DTorpoqqS7OP+Ruccjnh+fikoeZmMiwh9/hxu0AH3nQmXnF7EuYscufeREONShEx6pROi+0PDYOy/88fAZs3UHtW45KQGjHOVCiEKwL60ILg==
    jenkins-admin: AgC3sC/9RfCr+ehCa9R7tiMzuoBOHF8oAGAP+Hm+FIRGnADF/zXar2YCYFYznGYZAScZP4YnuWLFzPQCdQGmvHJ5n2ot6rjJdmMYq/vehKNGwyjW4uHmv6yxu63ZwX0SBvCTgBNO/B6unp7RD8psfz2GI1pRUnPi0m9Ij+KDznFc+y8GZ7sblhEEpU8h0qsVBuCw4PCOx+w/MQnW2bP09sAnM0PtfjcmXWGrQ1kPXMj9xNGJSAQCeVKh64ojK2dX93zmCHIgvAlT3SwSNrhSGe/vTYVwTPr9pndjJpZgwgRz/wfrqt6QEs+NzbEUAL8JPNGbtUJtontlHW6DnjT9Nn+xoeteWtJ+nPuxgUJgiqaNONw0cZuqugENa4FRr2m07O3areJp1Kbdqb+tQQqFxQ2RprQFRpwUBM5XuU5TIBxqIv22MLV9r6kF3ygQ2fGAyP7uNrqxUe+kyoKpzNAuhqHMcKkZtjgryeP3jJTJAMtnRWs0s+kAXGA9Sah5X4YsTdCYkn3EXgJiUqZxmLi1TMqDnGvyn66pPauE0nV3NocT9KC/apz/vMa6UXjCt2o8PYj7yXfM1qBQDLnrgBhAVjSn6sHQ4lVuc9IoGZO1N8ZxWIOE8CDqcZsJXqEU05Lr/sz9wvm3zQ4YQ1qERbUsS9QVhDHmfY63PmJJqnjJcE84MW/4g0n/aCqYeQkPpA2IfihtoXVXAcaaMVabow==
  template:
    metadata:
      name: dev-ops-secret
      namespace: devops
    type: Opaque
