apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: devops-pod-monitor
  namespace: monitoring
  labels:
    release: devops
spec:
  namespaceSelector:
    matchNames:
      - devops
  selector:
    matchLabels:
      app: code-server # 나머지 pod는 monitor이 있기에 상관 x
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 30s
