apiVersion: v1
kind: Service
metadata:
    name: debian-repo-service
spec:
    ports:
        - port: 80
            targetPort:80
            protocol: TCP
            name: http
    selector:
        app: debian-repo-server
        app: debian-repo-helper
    